Intranet/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from django.urls import path, include

import clients

urlpatterns = [
    path('', include('main.urls', namespace='main:Home_Main')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('produtos.urls', namespace='products')),
    path('colaborator/', include('colaborator.urls', namespace='colaborators')),
    path('departments/', include('departments.urls', namespace='departments')),
    path("workOrder/", include('workOrder.urls', namespace="workOrder")),
    path("clients/", include('clients.urls', namespace="clients")),
    path("settings/", include('settings.urls', namespace="settings")),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "main"

urlpatterns = [
    path('', views.Home, name = 'Home_Main')
]

produtos/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.Products, name = 'Home_Products'),
    path('product/<int:id>', views.ViewProduct, name = 'View_Product'),
    
    path('newProduct/', views.NewProduct, name = 'New_Products'),
    path('newitem/<int:id>', views.NewItem, name = 'New_Item'),
    path('newfile/<int:id>', views.NewFile, name = 'New_File'),
    path("newSegment/", views.NewSegment, name="New_Segment"),
    path("newProductTip/", views.NewProductTip, name="New_Product_Tip"),
    path("newCategory/", views.NewCategory, name="New_Category"),
    path("newClass/", views.NewClass, name="New_Class"),
    
    path('viewSegment/', views.ViewSegment, name = 'View_Segment_Products'),
    path('viewProductTip/', views.ViewProductTip, name = 'View_ProductTip_Products'),
    path('viewCategory/', views.ViewCategory, name = 'View_Category_Products'),
    path('viewClass/', views.ViewClass, name = 'View_Class_Products'),
    
    path('update/<int:id>', views.UpdateProduct, name = 'Update_Product'),
    path('updateSegment/<int:id>', views.UpdateSegment, name = 'Update_Segment_Products'),
    path('updateProductTip/<int:id>', views.UpdateProductTip, name = 'Update_ProductTip_Products'),
    path('updateCategory/<int:id>', views.UpdateCategory, name = 'Update_Category_Products'),
    path('updateClass/<int:id>', views.UpdateClass, name = 'Update_Class_Products'),

    path('delete/<int:id>', views.DeleteProduct, name = 'Delete_Product'),
    path('deleteitem/<int:id>', views.DeleteItem, name = 'Delete_Item'),
    path('deletefile/<int:id>', views.DeleteFile, name = 'Delete_file'),
    path('deleteSegment/<int:id>', views.DeleteSegment, name = 'Delete_Segment_Product'),
    path('deleteProductTip/<int:id>', views.DeleteProductTip, name = 'Delete_ProductTip_Product'),
    path('deleteCategory/<int:id>', views.DeleteCategory, name = 'Delete_Category_Product'),
    path('deleteClassProduct/<int:id>', views.DeleteClassProduct, name = 'Delete_Class_Product'),

    path('downloaditem/<int:id>', views.DownloadItem, name = 'Download_Item'),

    path('serialNumber/', views.SerialNumber, name = 'Serial_Number'),
    path('newSerialNumber/', views.GenerateSerial, name = 'Generate_SerialNumber'),
    path("serialNumberid/<int:id>", views.GenerateSerialSingle , name="Generate_Single_SerialNumber"),
    path("getPartNumber/<int:id>", views.GetPartNumber, name="PartNumber"),   
    path('customerProducts/', views.CustomerProducts, name="Customer_Products"),
    path('NewCustomerProducts/', views.NewCustomerProducts, name="New_Customer_Products")
]

settings/urls.py
from django.urls import path
from . import views

app_name = "settings"

urlpatterns = [
    path('', views.Settings, name = 'Settings_Main'),
    path('products', views.ProductSettings, name = 'Product_Settings'),
    path('workorder', views.WorkOrderSettings, name = 'WorkOder_Settings')
]

workOrder/urls.py
from django.urls import path
from . import views

app_name = 'workOrder'

urlpatterns = [
    path("workOrder/", views.WorkOrderHome, name="Home_WorkOrder"),
    path("NewWorkOrder/", views.NewWorkOrder, name="New_WorkOrder"),
    path("UpdateWorkOrder/<int:id>", views.UpdateWorOrder, name="Update_WorkOrder"),
    path("DeleteWorkOrder/<int:id>", views.DeleteWorkOrder, name="Delete_WorkOrder")
]

settings/models.py
from django.db import models
from produtos.models import CategoriaProduto, ClasseProduto, Produto, Segmento, TipoProduto

class ConfiguracoesProduto(models.Model):
    produto = models.ForeignKey(Produto, verbose_name="produto", on_delete=models.CASCADE)
    segmento = models.ForeignKey(Segmento, verbose_name="segmento", on_delete=models.CASCADE)
    tipoProduto = models.ForeignKey(TipoProduto, verbose_name="tipo de produto", on_delete=models.CASCADE)
    categoriaProduto = models.ForeignKey(CategoriaProduto, verbose_name="Categoria de produto", on_delete=models.CASCADE)
    classeProduto = models.ForeignKey(ClasseProduto, verbose_name="Classe de produto", on_delete=models.CASCADE)

settings/views.py
from django.db.models.query import EmptyQuerySet
from django.http import request
from django.contrib.auth import login
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from produtos.models import CategoriaProduto, ClasseProduto, Segmento, TipoProduto
from workOrder.models import OrdemServico
def Settings(request):
    return render(request, 'settings/Settings.html')

def ProductSettings(request):
    settingsSegmentsList = Segmento.objects.all().order_by('-dateCriacao')
    paginator = Paginator(settingsSegmentsList, 5)
    page = request.GET.get('page1')
    try:
        settingsSegments = paginator.get_page(page)
    except PageNotAnInteger:
        settingsSegments = paginator.page(1)
    except EmptyPage:
        settingsSegments = paginator.page(paginator.num_pages)
    
    settingsTipProductsList = TipoProduto.objects.all().order_by('-dateCriacao')
    paginator = Paginator(settingsTipProductsList, 5)
    page = request.GET.get('page2')
    try:
        settingsTipProducts = paginator.get_page(page)
    except PageNotAnInteger:
        settingsTipProducts = paginator.page(1)
    except EmptyPage:
        settingsTipProducts = paginator.page(paginator.num_pages)
    
    settingsCategoriesList = CategoriaProduto.objects.all().order_by('-dateCriacao')
    paginator = Paginator(settingsCategoriesList, 5)
    page = request.GET.get('page3')
    try:
        settingsCategories = paginator.get_page(page)
    except PageNotAnInteger:
        settingsCategories = paginator.page(1)
    except EmptyPage:
        settingsCategories = paginator.page(paginator.num_pages)
    
    settingsClassesList = ClasseProduto.objects.all().order_by('-dateCriacao')
    paginator = Paginator(settingsClassesList, 5)
    page = request.GET.get('page4')
    try:
        settingsClasses = paginator.get_page(page)
    except PageNotAnInteger:
        settingsClasses = paginator.page(1)
    except EmptyPage:
        settingsClasses = paginator.page(paginator.num_pages)

    context = {
        'settingsSegments': settingsSegments,
        'settingsTipProducts': settingsTipProducts,
        'settingsCategories': settingsCategories,
        'settingsClasses': settingsClasses
    }
    return render(request, 'settings/ProductSettings.html', context)

def WorkOrderSettings(request):
    workOrdersList = OrdemServico.objects.all().order_by('-dateCriacao')
    paginator = Paginator(workOrdersList, 10)
    page = request.GET.get('page')
    workOrders = paginator.get_page(page)
    context = {
        'workOrders': workOrders
    }
    return render(request, 'settings/WorkOrderSettings.html', context)

templates/settings/ProductSettings.html
{% extends 'base.html' %}

{% block title %}Configurações{% endblock %}

{% block content %}

    <a href="{% url 'settings:Settings_Main' %}">
        <i class="far fa-arrow-alt-circle-left fa-2x"></i>
    </a>        
    <div class="container title">
        <h1>Configurações de Produtos</h1>
    </div>
    
    <div class="offset-1 col-4 settings-segment">
        <h3>Segmentos</h3>
        <div class="products">
            <a href="{% url 'products:New_Segment' %}" class="add-comum"> 
                <div class="col-3 div-comum-add">
                    <i class="fas fa-plus comum"></i>Adicionar
                </div>
            </a>
        </div>
        <table class="table table-striped table-hover table-bordered tab-segment-settings">
            <thead>
                <tr>
                    <th scope="col">nome</th>
                    <th scope="col">sigla</th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="far fa-edit"></i>
                        </div>
                    </th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="fas fa-trash"></i>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for settingsSegment in settingsSegments %}
                <tr scope="row">
                    <td>
                        {{ settingsSegment.nome }}
                    </td>
                    <td>
                        {{ settingsSegment.sigla }}
                    </td>
                    <td>
                        <a href="{% url 'products:Update_Segment_Products' settingsSegment.id %}" class="icon">
                            <div class="col">
                                <i class="far fa-edit"></i>
                            </div>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'products:Delete_Segment_Product' settingsSegment.id %}" class="icon">
                            <div class="col">
                                <i class="fas fa-trash"></i>
                            </div>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if settingsSegments.has_previous %}
                    <a href="?page={{settingsSegments.previous_page_number}}" class="fas fa-arrow-left"></a>
                {% endif %}
                
                {% if settingsSegments.paginator.num_pages %}
                <span class="current">
                    {{settingsSegments.number}} de {{settingsSegments.paginator.num_pages}}
                </span>
                {% endif %}

                {% if settingsSegments.has_next %}
                    <a href="?page={{settingsSegments.next_page_number}}" class="fas fa-arrow-right"></a>
                {% endif %}
            </span>
        </div>
    </div>

    <div class="offset-1 col-4 settings-tip-products">
        <h3>Tipos de Produto</h3>
        <div class="products">
            <a href="{% url 'products:New_Product_Tip' %}" class="add-comum"> 
                <div class="col-3 div-comum-add">
                    <i class="fas fa-plus comum"></i>Adicionar
                </div>
            </a>
        </div>
        <table class="table table-striped table-hover table-bordered tab-tipproducts-settings">
            <thead>
                <tr>
                    <th scope="col">nome</th>
                    <th scope="col">sigla</th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="far fa-edit"></i>
                        </div>
                    </th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="fas fa-trash"></i>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for settingsTipProduct in settingsTipProducts %}
                <tr scope="row">
                    <td>
                        {{ settingsTipProduct.nome }}
                    </td>
                    <td>
                        {{ settingsTipProduct.sigla }}
                    </td>
                    <td>
                        <a href="{% url 'products:Update_ProductTip_Products' settingsTipProduct.id %}" class="icon">
                            <div class="col">
                                <i class="far fa-edit"></i>
                            </div>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'products:Delete_ProductTip_Product' settingsTipProduct.id %}" class="icon">
                            <div class="col">
                                <i class="fas fa-trash"></i>
                            </div>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    

        <div class="pagination">
            <span class="step-links">
                {% if settingsTipProducts.has_previous %}
                    <a href="?page2={{settingsTipProducts.previous_page_number}}" class="fas fa-arrow-left"></a>
                {% endif %}
                
                {% if settingsTipProducts.paginator.num_pages %}
                <span class="current">
                    {{settingsTipProducts.number}} de {{settingsTipProducts.paginator.num_pages}}
                </span>
                {% endif %}

                {% if settingsTipProducts.has_next %}
                    <a href="?page2={{settingsTipProducts.next_page_number}}" class="fas fa-arrow-right"></a>
                {% endif %}
            </span>
        </div>
    </div>

    <div class="offset-1 col-4 settings-category">
        <h3>Categorias</h3>
        <div class="products">
            <a href="{% url 'products:New_Category' %}" class="add-comum"> 
                <div class="col-3 div-comum-add">
                    <i class="fas fa-plus comum"></i>Adicionar
                </div>
            </a>
        </div>
        <table class="table table-striped table-hover table-bordered tab-category-settings">
            <thead>
                <tr>
                    <th scope="col">nome</th>
                    <th scope="col">sigla</th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="far fa-edit"></i>
                        </div>
                    </th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="fas fa-trash"></i>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for settingsCategory in settingsCategories %}
                <tr scope="row">
                    <td>
                        {{ settingsCategory.nome }}
                    </td>
                    <td>
                        {{ settingsCategory.sigla }}
                    </td>
                    <td>
                        <a href="{% url 'products:Update_Category_Products' settingsCategory.id %}" class="icon">
                            <div class="col">
                                <i class="far fa-edit"></i>
                            </div>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'products:Delete_Category_Product' settingsCategory.id %}" class="icon">
                            <div class="col">
                                <i class="fas fa-trash"></i>
                            </div>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    

        <div class="pagination">
            <span class="step-links">
                {% if settingsCategories.has_previous %}
                    <a href="?page3={{settingsCategories.previous_page_number}}" class="fas fa-arrow-left"></a>
                {% endif %}
                
                {% if settingsCategories.paginator.num_pages %}
                <span class="current">
                    {{settingsCategories.number}} de {{settingsCategories.paginator.num_pages}}
                </span>
                {% endif %}

                {% if settingsCategories.has_next %}
                    <a href="?page3={{settingsCategories.next_page_number}}" class="fas fa-arrow-right"></a>
                {% endif %}
            </span>
        </div>
    </div>

    <div class="offset-1 col-4 settings-class">
        <h3>Classes</h3>
        <div class="products">
            <a href="{% url 'products:New_Class' %}" class="add-comum"> 
                <div class="col-3 div-comum-add">
                    <i class="fas fa-plus comum"></i>Adicionar
                </div>
            </a>
        </div>
        <table class="table table-striped table-hover table-bordered tab-classes-settings">
            <thead>
                <tr>
                    <th scope="col">nome</th>
                    <th scope="col">sigla</th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="far fa-edit"></i>
                        </div>
                    </th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="fas fa-trash"></i>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody id="#">
                {% for settingsClass in settingsClasses %}
                <tr scope="row">
                    <td>
                        {{ settingsClass.nome }}
                    </td>
                    <td>
                        {{ settingsClass.sigla }}
                    </td>
                    <td>
                        <a href="{% url 'products:Update_Class_Products' settingsClass.id %}" class="icon">
                            <div class="col">
                                <i class="far fa-edit"></i>
                            </div>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'products:Delete_Class_Product' settingsClass.id %}" class="icon">
                            <div class="col">
                                <i class="fas fa-trash"></i>
                            </div>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    

        <div class="pagination">
            <span class="step-links">
                {% if settingsClasses.has_previous %}
                    <a href="?page4={{settingsClasses.previous_page_number}}" class="fas fa-arrow-left"></a>
                {% endif %}
                
                {% if settingsClasses.paginator.num_pages %}
                <span class="current">
                    {{settingsClasses.number}} de {{settingsClasses.paginator.num_pages}}
                </span>
                {% endif %}

                {% if settingsClasses.has_next %}
                    <a href="?page4={{settingsClasses.next_page_number}}" class="fas fa-arrow-right"></a>
                {% endif %}
            </span>
        </div>
    </div>

{% endblock %}

templates/settings/Settings.html
{% extends 'base.html' %}

{% block title %}Configurações{% endblock %}

{% block content %}

    <a href="{% url 'main:Home_Main' %}">
        <i class="far fa-arrow-alt-circle-left fa-2x"></i>
    </a>        
    <div class="container title">
        <h1>Configurações</h1>
    </div>

    <div class="offset-1 col-10 add-all-div">
        <a href="{% url 'settings:Product_Settings' %}" class="settings">
            <div class="col-2 div-settings-all">
                <i class="fas fa-plus all"></i>Produtos
            </div>
        </a>
        <a href="#" class="settings">
            <div class="col-2 div-settings-all">
                <i class="fas fa-plus all"></i>Número de Série
            </div>
        </a>
        <a href="{% url 'settings:WorkOder_Settings' %}" class="settings">
            <div class="col-2 div-settings-all">
                <i class="fas fa-plus all"></i>Ordem de Serviço
            </div>
        </a>
        <a href="#" class="settings">
            <div class="col-2 div-settings-all">
                <i class="fas fa-plus all"></i>Usuários
            </div>
        </a>
        <a href="#" class="settings">
            <div class="col-2 div-settings-all">
                <i class="fas fa-plus all"></i>Departamentos
            </div>
        </a>
    </div>

{% endblock %}

templates/settings/WorkOrderSettings.html
{% extends 'base.html' %}

{% block title %}Produtos{% endblock %}

{% block content %}

    <a href="{% url 'settings:Settings_Main' %}">
        <i class="far fa-arrow-alt-circle-left fa-2x"></i>
    </a>        
    <div class="container title">
        <h1>Configurações de Ordem de Serviço</h1>
    </div>

    <div class="offset-1 col-4">
        <h3>Ordem de Serviços</h3>
        <table class="table table-striped table-hover table-bordered tab-workorder-settings">
            <thead>
                <tr>
                    <th scope="col">Número</th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="far fa-edit"></i>
                        </div>
                    </th>
                    <th scope="col" class="col-sm-1">
                        <div class="col">
                            <i class="fas fa-trash"></i>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for workOrder in workOrders %}
                <tr scope="row">
                    <td>
                        {{ workOrder.OS }}
                    </td>
                    <td>
                        <a href="{% url 'workOrder:Update_WorkOrder' workOrder.id %}" class="icon">
                            <div class="col">
                                <i class="far fa-edit"></i>
                            </div>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'workOrder:Delete_WorkOrder' workOrder.id %}" class="icon">
                            <div class="col">
                                <i class="fas fa-trash"></i>
                            </div>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if workOrders.has_previous %}
                    <a href="?page={{workOrders.previous_page_number}}" class="fas fa-arrow-left"></a>
                {% endif %}
                
                {% if workOrders.paginator.num_pages %}
                <span class="current">
                    {{workOrders.number}} de {{workOrders.paginator.num_pages}}
                </span>
                {% endif %}

                {% if workOrders.has_next %}
                    <a href="?page={{workOrders.next_page_number}}" class="fas fa-arrow-right"></a>
                {% endif %}
            </span>
        </div>
    </div>

{% endblock %}