Intranet/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from django.urls import path, include

import clients

urlpatterns = [
    path('', include('main.urls', namespace='main:Home_Main')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('produtos.urls', namespace='products')),
    path('colaborator/', include('colaborator.urls', namespace='colaborators')),
    path('departments/', include('departments.urls', namespace='departments')),
    path("workOrder/", include('workOrder.urls', namespace="workOrder")),
    path("clients/", include('clients.urls', namespace="clients")),
    path("settings/", include('settings.urls', namespace="settings")),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path
from . import views
from . import models

app_name = 'clients'

urlpatterns = [
    path('', views.HomeClients, name="Home_Clients"),
    path('addClient', views.NewClient, name="New_Client")
]

main/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "main"

urlpatterns = [
    path('', views.Home, name = 'Home_Main')
]

produtos/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.Products, name = 'Home_Products'),
    path('product/<int:id>', views.ViewProduct, name = 'View_Product'),
    
    path('newProduct/', views.NewProduct, name = 'New_Products'),
    path('newitem/<int:id>', views.NewItem, name = 'New_Item'),
    path('newfile/<int:id>', views.NewFile, name = 'New_File'),
    path("newSegment/", views.NewSegment, name="New_Segment"),
    path("newProductTip/", views.NewProductTip, name="New_Product_Tip"),
    path("newCategory/", views.NewCategory, name="New_Category"),
    path("newClass/", views.NewClass, name="New_Class"),
    
    path('viewSegment/', views.ViewSegment, name = 'View_Segment_Products'),
    path('viewProductTip/', views.ViewProductTip, name = 'View_ProductTip_Products'),
    path('viewCategory/', views.ViewCategory, name = 'View_Category_Products'),
    path('viewClass/', views.ViewClass, name = 'View_Class_Products'),
    
    path('update/<int:id>', views.UpdateProduct, name = 'Update_Product'),
    path('updateSegment/<int:id>', views.UpdateSegment, name = 'Update_Segment_Products'),
    path('updateProductTip/<int:id>', views.UpdateProductTip, name = 'Update_ProductTip_Products'),
    path('updateCategory/<int:id>', views.UpdateCategory, name = 'Update_Category_Products'),
    path('updateClass/<int:id>', views.UpdateClass, name = 'Update_Class_Products'),

    path('delete/<int:id>', views.DeleteProduct, name = 'Delete_Product'),
    path('deleteitem/<int:id>', views.DeleteItem, name = 'Delete_Item'),
    path('deletefile/<int:id>', views.DeleteFile, name = 'Delete_file'),
    path('deleteSegment/<int:id>', views.DeleteSegment, name = 'Delete_Segment_Product'),
    path('deleteProductTip/<int:id>', views.DeleteProductTip, name = 'Delete_ProductTip_Product'),
    path('deleteCategory/<int:id>', views.DeleteCategory, name = 'Delete_Category_Product'),
    path('deleteClassProduct/<int:id>', views.DeleteClassProduct, name = 'Delete_Class_Product'),

    path('downloaditem/<int:id>', views.DownloadItem, name = 'Download_Item'),

    path('serialNumber/', views.SerialNumber, name = 'Serial_Number'),
    path('newSerialNumber/', views.GenerateSerial, name = 'Generate_SerialNumber'),
    path("serialNumberid/<int:id>", views.GenerateSerialSingle , name="Generate_Single_SerialNumber"),
    path("getPartNumber/<int:id>", views.GetPartNumber, name="PartNumber"),   
    path('customerProducts/', views.CustomerProducts, name="Customer_Products"),
    path('NewCustomerProducts/', views.NewCustomerProducts, name="New_Customer_Products")
]

settings/urls.py
from django.urls import path
from . import views

app_name = "settings"

urlpatterns = [
    path('', views.Settings, name = 'Settings_Main'),
    path('products', views.ProductSettings, name = 'Product_Settings'),
    path('workorder', views.WorkOrderSettings, name = 'WorkOder_Settings')
]

workOrder/urls.py
from django.urls import path
from . import views

app_name = 'workOrder'

urlpatterns = [
    path("workOrder/", views.WorkOrderHome, name="Home_WorkOrder"),
    path("NewWorkOrder/", views.NewWorkOrder, name="New_WorkOrder"),
    path("UpdateWorkOrder/<int:id>", views.UpdateWorOrder, name="Update_WorkOrder"),
    path("DeleteWorkOrder/<int:id>", views.DeleteWorkOrder, name="Delete_WorkOrder")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bs/bootstrap.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}"%>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}%">
    <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
</head>
<body>
    {% if user.is_authenticated %}
    <div class="sidebar">
        <div class="logo_content">
            <div class="logo">
                <img src="{% static 'img/logo-base.png' %}" class="img-base"/>
                <div class="logo_name">Innova</div>
            </div>
            <i class="fas fa-bars" id="btn-menu"></i>
        </div>
        <ul class="nav_list">
            <li>
                <a href="{%url 'main:Home_Main'%}">
                    <i class="fas fa-grip-vertical"></i>
                    <span class="link_name">Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{%url 'products:Home_Products'%}">
                    <i class="fas fa-archive"></i>
                    <span class="link_name">Produtos</span>
                </a>
            </li>
            <li>
                <a href="{%url 'products:Customer_Products'%}">
                    <i class="fas fa-book-open"></i>
                    <span class="link_name">Produtos de Clientes</span>
                </a>
            </li>
            <li>
                <a href="{%url 'products:Serial_Number'%}">
                    <i class="fas fa-key"></i>
                    <span class="link_name">Número de Série</span>
                </a>
            </li> 
            <li>
                <a href="{% url 'workOrder:Home_WorkOrder' %}">
                    <i class="fas fa-wallet"></i>
                    <span class="link_name">Ordem de Serviço</span>
                </a>
            </li> 
            <li>
                <a href="{% url 'clients:Home_Clients' %}">
                    <i class="fas fa-address-book"></i>
                    <span class="link_name">Clientes</span>
                </a>
            </li>
            <li>
                <a href="{% url 'colaborators:Home_Colaborator' %}">
                    <i class="fas fa-user"></i>
                    <span class="link_name">Usuários</span>
                </a>
            </li>
            <li>
                <a href="{% url 'departments:Home_Departments' %}">
                    <i class="fas fa-building"></i>
                    <span class="link_name">Departamentos</span>
                </a>
            </li>
            <li>
                <a href="{% url 'settings:Settings_Main' %}">
                    <i class="fas fa-cog"></i>
                    <span class="link_name">Configurações</span>
                </a>
            </li>
        </ul>
        
        <div class="profile_content">
            <div class="profile">
                <div class="profile_details">
                    <div class="name_job">
                        <div class="name">{{ user.username }}</div>
                        <div class="job">{{ departamento.nome }}</div>
                    </div>
                </div>
                <div class="version">
                    v1.1.4
                </div>
                <a href="{%url 'logout'%}">
                    <i class="fas fa-sign-out-alt" id="logout"></i>
                </a>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="home_content">
        {% block content %}
        {% endblock %}
    </div>
    <script type="text/javascript." scr="{% static 'js/scripts.js' %}"></script>
    <script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/bs/bootstrap.js' %}"></script>
    <script src="https://kit.fontawesome.com/8f8a4bcfa0.js" crossorigin="anonymous"></script>
</body>
</html>