Intranet/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from django.urls import path, include

import clients

urlpatterns = [
    path('', include('main.urls', namespace='main:Home_Main')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('produtos.urls', namespace='products')),
    path('colaborator/', include('colaborator.urls', namespace='colaborators')),
    path('departments/', include('departments.urls', namespace='departments')),
    path("workOrder/", include('workOrder.urls', namespace="workOrder")),
    path("clients/", include('clients.urls', namespace="clients")),
    path("settings/", include('settings.urls', namespace="settings")),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "main"

urlpatterns = [
    path('', views.Home, name = 'Home_Main')
]

produtos/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.Products, name = 'Home_Products'),
    path('product/<int:id>', views.ViewProduct, name = 'View_Product'),
    
    path('newProduct/', views.NewProduct, name = 'New_Products'),
    path('newitem/<int:id>', views.NewItem, name = 'New_Item'),
    path('newfile/<int:id>', views.NewFile, name = 'New_File'),
    path("newSegment/", views.NewSegment, name="New_Segment"),
    path("newProductTip/", views.NewProductTip, name="New_Product_Tip"),
    path("newCategory/", views.NewCategory, name="New_Category"),
    path("newClass/", views.NewClass, name="New_Class"),
    
    path('viewSegment/', views.ViewSegment, name = 'View_Segment_Products'),
    path('viewProductTip/', views.ViewProductTip, name = 'View_ProductTip_Products'),
    path('viewCategory/', views.ViewCategory, name = 'View_Category_Products'),
    path('viewClass/', views.ViewClass, name = 'View_Class_Products'),
    
    path('update/<int:id>', views.UpdateProduct, name = 'Update_Product'),
    path('updateSegment/<int:id>', views.UpdateSegment, name = 'Update_Segment_Products'),
    path('updateProductTip/<int:id>', views.UpdateProductTip, name = 'Update_ProductTip_Products'),
    path('updateCategory/<int:id>', views.UpdateCategory, name = 'Update_Category_Products'),
    path('updateClass/<int:id>', views.UpdateClass, name = 'Update_Class_Products'),

    path('delete/<int:id>', views.DeleteProduct, name = 'Delete_Product'),
    path('deleteitem/<int:id>', views.DeleteItem, name = 'Delete_Item'),
    path('deletefile/<int:id>', views.DeleteFile, name = 'Delete_file'),
    path('deleteSegment/<int:id>', views.DeleteSegment, name = 'Delete_Segment_Product'),
    path('deleteProductTip/<int:id>', views.DeleteProductTip, name = 'Delete_ProductTip_Product'),
    path('deleteCategory/<int:id>', views.DeleteCategory, name = 'Delete_Category_Product'),
    path('deleteClassProduct/<int:id>', views.DeleteClassProduct, name = 'Delete_Class_Product'),

    path('downloaditem/<int:id>', views.DownloadItem, name = 'Download_Item'),

    path('serialNumber/', views.SerialNumber, name = 'Serial_Number'),
    path('newSerialNumber/', views.GenerateSerial, name = 'Generate_SerialNumber'),
    path("serialNumberid/<int:id>", views.GenerateSerialSingle , name="Generate_Single_SerialNumber"),
    path("getPartNumber/<int:id>", views.GetPartNumber, name="PartNumber"),   
    path('customerProducts/', views.CustomerProducts, name="Customer_Products"),
    path('NewCustomerProducts/', views.NewCustomerProducts, name="New_Customer_Products")
]

settings/urls.py
from django.urls import path
from . import views

app_name = "settings"

urlpatterns = [
    path('', views.Settings, name = 'Settings_Main'),
    path('products', views.ProductSettings, name = 'Product_Settings'),
    path('workorder', views.WorkOrderSettings, name = 'WorkOder_Settings')
]

produtos/views.py
import os
import datetime
from django.conf import settings
from django.http import HttpResponse
from django.core.files.base import File
from django.core.paginator import Paginator
from django.forms.widgets import SelectMultiple
from django.http import response
from django.http.response import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from produtos.models import CategoriaProduto, ClasseProduto, NumeroSerie, Produto, Item, Arquivo, ProdutoCliente, Segmento, TipoProduto, PartNumber
from produtos.forms import CategoryForm, ClassProductForm, CustomerProductsForm, ItemForm, PartNumberForm, ProdutoForm, FileForm, SegmentForm, SerialNumberForm, TipForm, WorkOrderForm, produtoSelect
from clients.models import Cliente
def Products(request):
    """  View of main page of products """
    search = request.GET.get('search')
    
    if search:
        productsList = Produto.objects.filter(nome__icontains = search)
        paginator = Paginator(productsList, 10)
        page = request.GET.get('page')
        products = paginator.get_page(page)
    else:
        productsList = Produto.objects.all().order_by('-dateCriacao')
        order = request.GET.get('order')
        if order == 'Produto':
            productsList = Produto.objects.all().order_by('nome')
        elif order == 'Equipamento':
            productsList = Produto.objects.all().order_by('equipamento')
        elif order == 'Codigo':
            productsList = Produto.objects.all().order_by('codigo')
        elif order == 'Segmento':
            productsList = Produto.objects.all().order_by('segmento')
            
        paginator = Paginator(productsList, 10)
        page = request.GET.get('page')
        products = paginator.get_page(page)
    context = {'products' : products}
    return render(request, 'produtos/Products.html', context)

def NewProduct(request):
    """  View of new product  """
    createProduct = ProdutoForm()
    if request.method == 'POST':
        createProduct = ProdutoForm(request.POST or None)
        if createProduct.is_valid():
            product = createProduct.save(commit = False)
            product.descontinuado = False
            product.save()
            return redirect('products:Home_Products')
    else:
        createProduct = ProdutoForm()
    context = {'createProduct' : createProduct}
    return render(request, 'produtos/NewProduct.html', context)

def NewItem(request, id):
    """  View of new items for products  """
    product = get_object_or_404(Produto, id=id)
    createItem = ItemForm()
    if request.method == 'POST':
        createItem = ItemForm(request.POST, request.FILES)
        if createItem.is_valid():
            item = createItem.save(commit=False)
            item.produto = product
            item.save()
            return redirect('produtos/View_Product', product)
    else:
        createItem = ItemForm()
    context = {'createItem' : createItem, 'product' : product}
    return render(request, 'produtos/NewItem.html', context)

def NewFile(request, id):
    """  view of new file  for products  """
    product = get_object_or_404(Produto, id=id)
    fileForm = FileForm()
    if request.method == 'POST':
        fileForm = FileForm(request.POST, request.FILES)
        if fileForm.is_valid():
            file = fileForm.save(commit=False)
            file.produto = product
            file.save()
            return redirect('/products/')  
    else:
        fileForm = FileForm()
    return render(request, 'produtos/NewFile.html', {'fileForm' : fileForm})

def NewSegment(request):
    """  View of new segment  """
    createSegment = SegmentForm()
    if request.method == 'POST':
        createSegment = SegmentForm(request.POST or None)
        if createSegment.is_valid():
            createSegment.save()
            return redirect('/products')
    else:
        createSegment = SegmentForm()
    context = {'createSegment' : createSegment}
    return render(request, 'produtos/NewSegment.html', context)

def NewProductTip(request):
    """  View of new product tip  """
    createTip = TipForm()
    if request.method == 'POST':
        createTip = TipForm(request.POST or None)
        if createTip.is_valid():
            createTip.save()
            return redirect('/products')
    else:
        createTip = TipForm()
    context = {'createTip' : createTip}
    return render(request, 'produtos/NewProductTip.html', context)

def NewCategory(request):
    """  View of ney categories  """
    createCategory = CategoryForm()
    if request.method == 'POST':
        createCategory = CategoryForm(request.POST or None)
        if createCategory.is_valid():
            createCategory.save()
            return redirect('/products')
    else:
        createCategory = CategoryForm()
    context = {'createCategory' : createCategory}
    return render(request, 'produtos/NewCategory.html', context)

def NewClass(request):
    """  View of new classes  """
    createClassProduct = ClassProductForm()
    if request.method == 'POST':
        createClassProduct = ClassProductForm(request.POST or None)
        if createClassProduct.is_valid():
            createClassProduct.save()
            return redirect('/products')
    else:
        createClassProduct = ClassProductForm()
    context = {'createClassProduct' : createClassProduct}
    
    return render(request, 'produtos/NewClass.html', context)

def NewCustomerProducts(request):
    """  View of new customer products  """
    createCustomerProducts = CustomerProductsForm()
    if request.method == 'POST':
        createCustomerProducts = CustomerProductsForm(request.POST, request.FILES)
        if createCustomerProducts.is_valid():
            createCustomerProducts.save()
            return redirect('products:Customer_Products')
    else:
        createCustomerProducts = CustomerProductsForm()
    context = {'createCustomerProducts' : createCustomerProducts}
    return render(request, 'produtos/NewCustomerProducts.html', context)

def ViewProduct(request, id):
    """  View of single products  """
    context = []
    items = Item.objects.all().filter(produto_id = id).order_by('-revisao')
    filesList = Arquivo.objects.all().filter(produto_id = id).order_by('-revisao')
    product = get_object_or_404(Produto, id = id)
    paginator = Paginator(filesList, 10)
    page = request.GET.get('page')
    files = paginator.get_page(page)
    context = {
        'product': product,
        'items': items,
        'files': files,
    }
    return render(request, 'produtos/Product.html', context)

def ViewSegment(request):
    """  View of segments of products  """
    segments = Segmento.objects.all().order_by('-dateCriacao')
    return render(request, 'produtos/ViewSegment.html', {'segments' : segments})

def ViewProductTip(request):
    """  View of product tipes of products  """
    productTipes = TipoProduto.objects.all().order_by('-dateCriacao')
    return render(request, 'produtos/ViewProductTip.html', {'productTipes' : productTipes})

def ViewCategory(request):
    """  View of categories of products"""
    categories = CategoriaProduto.objects.all().order_by('-dateCriacao')
    return render(request, 'produtos/ViewCategory.html', {'categories' : categories})

def ViewClass(request):
    """  View of classes """
    classes = ClasseProduto.objects.all().order_by('-dateCriacao')
    return render(request, 'produtos/ViewClass.html', {'classes' : classes})

def UpdateProduct(request, id):
    """  View of update product  """
    product = get_object_or_404(Produto, id = id)
    updateProduct = ProdutoForm(instance = product)
    if request.method == 'POST':
        updateProduct = ProdutoForm(request.POST or None, instance = product)
        if updateProduct.is_valid():
            updateProduct.save()
            return redirect('../')
        else:
            context = {'updateProduct' : updateProduct, 'product' : product}
            return render(request, 'produtos/UpdateProduct.html', context)
    else:
        context = {'updateProduct' : updateProduct, 'product' : product}
        return render(request, 'produtos/UpdateProduct.html', context)

def UpdateSegment(request, id):
    """  View of segment of product  """
    segment = get_object_or_404(Segmento, id = id)
    updateSegment = SegmentForm(instance = segment)
    if request.method == 'POST':
        updateSegment = SegmentForm(request.POST or None, instance = segment)
        if updateSegment.is_valid():
            updateSegment.save()
            return redirect('settings:Product_Settings')
        else:
            context = {'updateSegment' : updateSegment, 'segment' : segment}
            return render(request, 'produtos/UpdateSegment.html', context)
    else:
        context = {'updateSegment' : updateSegment, 'segment' : segment}
        return render(request, 'produtos/UpdateSegment.html', context)

def UpdateProductTip(request, id):
    """  View of update product tip  """
    productTip = get_object_or_404(TipoProduto, id = id)
    updateTip = TipForm(instance = productTip)
    if request.method == 'POST':
        updateTip = TipForm(request.POST or None, instance = productTip)
        if updateTip.is_valid():
            updateTip.save()
            return redirect('settings:Product_Settings')
        else:
            context = {'updateTip' : updateTip, 'productTip' : productTip}
            return render(request, 'produtos/UpdateProductTip.html', context)
    else:
        context = {'updateTip' : updateTip, 'productTip' : productTip}
        return render(request, 'produtos/UpdateProductTip.html', context)

def UpdateCategory(request, id):
    """  View of update category of product  """
    category = get_object_or_404(CategoriaProduto, id = id)
    updateCategory = CategoryForm(instance = category)

templates/produtos/DeleteCategory.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Excluir Categoria{% endblock %}

{% block content %}
    
    <a href="{% url 'settings:Product_Settings' %}">
        <i class="far fa-arrow-alt-circle-left fa-2x"></i>
    </a>
    <form method="POST">
        {% csrf_token %}
        <h1 class="title-form">Deseja excluir a categoria "{{category.nome}}"?</h1>
        <p class="confirm-delete">
            <input type="submit" value="Sim"/>
            <a href="../">Não</a>
        </p>

{% endblock %}

templates/produtos/Product.html
{% extends 'base.html' %}

{% block title %}{{ product.nome }}{% endblock %}

{% block content %}

    <a href="#">
        <i class="far fa-arrow-alt-circle-left fa-2x"></i>
    </a>
    <div class="title">
        <h1>{{ product.nome }}</h1>
    </div>

    <div class="offset-1 col-10 product-div">
        <a href="{% url 'products:Update_Product' product.id %}" class="edit-product">
            <div class="edit-div">
                <i class="fas fa-edit"></i>Editar
            </div>
        </a>

        <a href="{% url 'products:Delete_Product' product.id %}" class="del-product confirm-delete">
            <div class="col-2 del-product-div">
                <i class="fas fa-trash del-product-button"></i>Deletar Produto
            </div>
        </a>

        <table class="product-table">
            <tbody>
                <tr>
                    <td class=" col-2 product-item-title">
                        Ativo:
                    </td>
                    <td class="col-3 product-item">
                        {% if product.descontinuado == 0 %}
                            Sim
                        {% else %}
                            Não
                        {% endif %}
                    </td>
                    <td class="col-2 product-item-title">
                        Segmento:
                    </td>
                    <td class="col-3 product-item">
                        {{ product.segmento }}
                    </td>
                </tr>
                <tr>
                    <td class="col-2 product-item-title">
                        Nome:
                    </td>
                    <td class="col-3 product-item">
                        {{ product.nome }}
                    </td>
                    <td class="col-2 product-item-title">
                        Equipamento:
                    </td>
                    <td class="col-3 product-item">
                        {{ product.equipamento }}
                    </td>
                </tr>
                <tr>
                    <td class="col-2 product-item-title">
                        Acessório:
                    </td>
                    <td class="col-3 product-item">
                        {{ product.tipoProduto }}
                    </td>
                    <td class="col-2 product-item-title">
                        Categoria:
                    </td>
                    <td class="col-3 product-item">
                        {% if product.categoria %}
                            {{ product.categoria }}
                        {% else %}
                            Sem categoria
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="col-2 product-item-title">
                        Capacidade:
                    </td>
                    <td class="col-2 product-item">
                        {{ product.capacidade }} Ton
                    </td>
                    <td class="col-2 product-item-title ">
                        Largura:
                    </td>
                    <td class="col-2 product-item">
                        {{ product.largura }} mm
                    </td>
                </tr>
                <tr>
                    <td class="col-2 product-item-title">
                        Comprimento:
                    </td>
                    <td class="col-2 product-item">
                        {{ product.comprimento }} mm
                    </td>
                    <td class="col-2 product-item-title ">
                        Volume:
                    </td>
                    <td class="col-2 product-item">
                        {{ product.volume }} mm
                    </td>
                </tr>
                <tr>
                    <td class="col-2 product-item-title">
                        Espessua:
                    </td>
                    <td class="col-2 product-item">
                        {{ product.espessura }} mm
                    </td>
                    <td class="col-2 product-item-title">
                        Peso:
                    </td>
                    <td class="col-2 product-item">
                        {{ product.peso }} Kg
                    </td>
                </tr>
                <tr>
                    <td class="col-2 product-item-title">
                        Data de criação:
                    </td>
                    <td class="col-2 product-item">
                        {{ product.dateCriacao }}
                    </td>
                    <td class="col-2 product-item-title">
                        Última modificação:
                    </td>
                    <td class="col-2 product-item">
                        {{ product.dateUpdate }}
                    </td>
                </tr>
            </tbody>
        </table>

        <a href="{% url 'products:New_Item' product.id %}" class="add-item">
            <div class="col-2 item-div">
                <i class="fas fa-plus add-item-button"></i>Adicionar Pack
            </div>
        </a>

        <a href="{% url 'products:New_File' product.id %}" class="add-file">
            <div class="col-2 file-div">
                <i class="fas fa-plus add-file-button"></i>Adicionar Arquivo
            </div>
        </a>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="alert alert-{{message.tags}}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <!-- <div class="container download">
            <a href="#" class="download-all">
                <div class="col download-all-div">
                    <i class="fas fa-download download-all-button"></i>
                </div>
            </a>
        </div> -->

        <div class="container table-items">
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Revisao</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Tipo</th>
                        <th scope="col">PartNumber</th>
                        <th scope="col">Fabricação</th>
                        <th scope="col">Data de Criação</th>
                        <th scope="col">
                            <div class="col partnumber-div">
                                <i class="fas fa-clipboard-check"></i>
                            </div>
                        </th>
                        <th scope="col">
                            <div class="col download-div">
                                <i class="fas fa-download download-button"></i>
                            </div>
                        </th>
                        <th scope="col">
                            <div class="col del-div">
                                <i class="fas fa-trash del-button"></i>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                        <tr scope="row">
                            <td>
                                {{ item.revisao }}
                            </td>
                            <td>
                                {{ item.nome }}
                            </td>
                            <td>
                                Zip
                            </td>
                            <td>
                                -
                            </td>
                            <td>
                                -
                            </td>
                            <td>
                                {{ item.dateCriacao|date:"d/m/Y" }}
                            </td>
                            <td>
                                -
                            </td>
                            <td>
                                <a href="{{ item.file.url }}" class="download-item" download="{{ item.file.url }}">
                                    <div class="col download-item-div">
                                        <i class="fas fa-download download-button"></i>
                                    </div>
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'products:Delete_Item' item.id %}" class="del-item">
                                    <div class="col del-item-div">
                                        <i class="fas fa-trash del-item-button"></i>
                                    </div>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}

                    {% for file in files %}
                        <tr scope="row">
                            <td>
                                {{ file.revisao }}
                            </td>
                            <td>
                                {{ file.nome }}
                            </td>
                            <td>
                                {{ file.tipo }}
                            </td>
                            <td>
                                {% if file.partNumber %}
                                    {{ file.partNumber.partNumber }}
                                {% endif %}
                            </td>
                            <td>
                                {{ file.tipoFabricacao }}
                            </td>
                            <td>
                                {{ file.dateCriacao|date:"d/m/Y" }}
                            </td>
                            <td>
                                <a href="{% url 'products:PartNumber' file.id%}" class="get-partnumber">
                                    <div class="col get-partnumber-div">
                                        <i class="fas fa-clipboard-check"></i>
                                    </div>
                                </a>
                            </td>
                            <td>
                                <a href="{{ file.file.url }}" class="download-file" download="{{ file.file.url }}">
                                    <div class="col download-file-div">
                                        <i class="fas fa-download download-button"></i>
                                    </div>
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'products:Delete_file' file.id %}" class="del-file">
                                    <div class="col del-file-div">
                                        <i class="fas fa-trash del-file-button"></i>
                                    </div>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>        
            </table>
        </div>
        
        <div class="pagination">
            <span class="step-links">
                {% if files.has_previous %}
                    <a href="?page={{files.previous_page_number}}" class="fas fa-arrow-left"></a>
                {% endif %}
                
                {% if files.paginator.num_pages %}
                <span class="current">
                    {{files.number}} de {{files.paginator.num_pages}}
                </span>
                {% endif %}

                {% if products.has_next %}
                    <a href="?page={{files.next_page_number}}" class="fas fa-arrow-right"></a>
                {% endif %}
            </span>
        </div>
    </div>



{% endblock %}

templates/produtos/Products.html
{% extends 'base.html' %}

{% block title %}Produtos{% endblock %}

{% block content %}

    <a href="{% url 'main:Home_Main' %}">
        <i class="far fa-arrow-alt-circle-left fa-2x"></i>
    </a>        
    <div class="container title">
        <h1>Produtos</h1>
    </div>
    
    <div class="offset-1 col-10 add-all-div">
        <a href="{% url 'products:New_Products' %}" class="add-all">
            <div class="col-2 div-add-all">
                <i class="fas fa-plus all"></i>Adicionar
            </div>
        </a>

        {% if products|length > 0 %}

        <div class="col-3 search-div">
            <form method="GET" id="search-form">
                <input class="form-control" type="text" id="search" name="search" placeholder="Digite o nome do produto">
                <i class="fas fa-search" id="search-button"></i>
            </form>
        </div>

        {% endif %}

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="alert alert-{{message.tags}}"{% endif %}>
                        {{message}}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <form method="GET" id="order-product" style="margin-bottom: 1em;">
            <label for="order">Ordenar por:</label>

            <select id="order">
                <option label="Produto">Produto</option>
                <option label="Equipamento">Equipamento</option>
                <option label="Código">Codigo</option>
                <option label="Segmento">Segmento</option>
            </select>
            <input type="submit" class="btn btn-success ordenar" id="order" value="Ordenar">
        </form>

        <table class="table table-striped table-hover table-bordered tab-products">
            <thead>
                <tr>
                    <th scope="col">Produto</th>
                    <th scope="col">Equipamento</th>
                    <th scope="col">Código</th>
                    <th scope="col">Segmento</th>
                    <th scope="col">Volume</th>
                    <th scope="col">Largura</th>
                    <th scope="col">Espessura</th>
                    <th scope="col">Descontinuado</th>
                    <th scope="col" class="col-sm-1">Visualizar</th>
                </tr>
            </thead>
            <tbody id="product-table">
                {% for product in products %}
                <tr scope="row">
                    <td>
                        {{product.nome}}
                    </td>
                    <td>
                        {{product.equipamento}}
                    </td>
                    <td>
                        {{product.tipoProduto.sigla}}
                    </td>
                    <td>
                        {{product.segmento}}
                    </td>
                    <td>
                        {{product.capacidade}}
                    </td>
                    <td>
                        {{product.largura}}
                    </td>
                    <td>
                        {{product.espessura}}
                    </td>
                    <td>
                        {% if product.descontinuado == 0 %}
                            Não
                        {% else %}
                            Sim
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'products:View_Product' product.id %}" class="icon view-product">
                            <div class="col">
                                <i class="far fa-eye"></i>
                            </div>
                        </a>
                    </td>
                </tr>
                {% empty %}
                    <li>Nenhum produto cadastrado.</li>
                {% endfor %}
            </tbody>
        </table>



        <div class="pagination">
            <span class="step-links">
                {% if products.has_previous %}
                    <a href="?page={{products.previous_page_number}}" class="fas fa-arrow-left"></a>
                {% endif %}
                
                {% if products.paginator.num_pages %}
                <span class="current">
                    {{products.number}} de {{products.paginator.num_pages}}
                </span>
                {% endif %}

                {% if products.has_next %}
                    <a href="?page={{products.next_page_number}}" class="fas fa-arrow-right"></a>
                {% endif %}
            </span>
        </div>
    </div>

{% endblock %}