Intranet/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from django.urls import path, include

import clients

urlpatterns = [
    path('', include('main.urls', namespace='main:Home_Main')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('produtos.urls', namespace='products')),
    path('colaborator/', include('colaborator.urls', namespace='colaborators')),
    path('departments/', include('departments.urls', namespace='departments')),
    path("workOrder/", include('workOrder.urls', namespace="workOrder")),
    path("clients/", include('clients.urls', namespace="clients")),
    path("settings/", include('settings.urls', namespace="settings")),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

if settings.DEBUG:
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path
from . import views
from . import models

app_name = 'clients'

urlpatterns = [
    path('', views.HomeClients, name="Home_Clients"),
    path('addClient', views.NewClient, name="New_Client")
]

main/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "main"

urlpatterns = [
    path('', views.Home, name = 'Home_Main')
]

clients/models.py
from django.db import models
from django.db.models.fields import CharField, DateTimeField, IntegerField

class Cliente(models.Model):
    nome = CharField(max_length=50)
    cnpj = IntegerField()
    
    dateCriacao = DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nome

clients/forms.py
from django import forms
from django.db.models import fields
from django.forms.models import ModelForm
from .models import Cliente

class ClientForm(ModelForm):
    class Meta:
        model = Cliente
        fields = [
            'nome',
            'cnpj'
        ]
        
        labels = {
            'nome': ('Nome'),
            'cnpj': ('Cnpj')
        }

clients/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from clients.forms import ClientForm
from .models import Cliente

def HomeClients(request):
    search = request.GET.get('search')
    
    if search:
        clientsList = Cliente.objects.filter(nome__icontains = search)
        paginator = Paginator(clientsList, 10)
        page = request.GET.get('page')
        clients = paginator.get_page(page)
    else:    
        clientsList = Cliente.objects.all().order_by('-dateCriacao')
        paginator = Paginator(clientsList, 10)
        page = request.GET.get('page')
        clients = paginator.get_page(page)
    context = {'clients' : clients }
    return render(request, 'clients/HomeClients.html', context)

def NewClient(request):
    createClient = ClientForm()
    if request.method == 'POST':
        createClient = ClientForm(request.POST or None)
        if createClient.is_valid():
            createClient.save()
            return redirect('../../')
        
    else:
        createClient = ClientForm()
    
    context = {
        'createClient' : createClient
    }
            
    return render(request, 'clients/NewClient.html', context)

templates/clients/HomeClients.html
{% extends 'base.html' %}

{% block title %}Colaboradores{% endblock %}

{% block content %}

    <a href="{% url 'main:Home_Main' %}">
        <i class="far fa-arrow-alt-circle-left fa-2x"></i>
    </a>
    <div class="container title">
        <h1>Clientes</h1>
    </div>

    <div class="offset-1 col-10 add-all-div">
        <a href="{% url 'clients:New_Client' %}" class="add-all">
            <div class="col-2 div-add-all">
                <i class="fas fa-plus all"></i>Adicionar
            </div>
        </a>
        
        <div class="col-3 search-div">
            <form method="GET" id="search-form">
                <input class="form-control" type="text" id="search" name="search" placeholder="Digite o nome do produto">
                <i class="fas fa-search" id="search-button"></i>
            </form>
        </div>

        <table class="table table-striped table-hover table-bordered tab-clients">
            <thead>
                <tr>
                    {% comment %} <th scope="col">Num. Série</th> {% endcomment %}
                    <th scope="col">Nome</th>
                    <th scope="col">CNPJ</th>
                </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                <tr scope="row">
                    <td>
                        {{client.nome}}
                    </td>
                    <td>
                        {{client.cnpj}}
                    </td>
                </tr>
                {% empty %}
                    <p>Nenhum cliente cadastrado.</p>
                {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if clients.has_previous %}
                    <a href="?page={{clients.previous_page_number}}" class="fas fa-arrow-left"></a>
                {% endif %}
                
                {% if clients.paginator.num_pages %}
                <span class="current">
                    {{clients.number}} de {{clients.paginator.num_pages}}
                </span>
                {% endif %}

                {% if clients.has_next %}
                    <a href="?page={{clients.next_page_number}}" class="fas fa-arrow-right"></a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

templates/clients/NewClient.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Adicionar Cliente{% endblock %}

{% block content %}

    <a href="{% url 'clients:Home_Clients' %}">
        <i class="far fa-arrow-alt-circle-left fa-2x"></i>
    </a>
    <div class="container title">
        <h1>Cadastrar Cliente</h1>
    </div>
    
    <div class="offset-1 col-3">
        <form method="POST">
            {% csrf_token %}
            {{ createClient|crispy }}
            <input type="submit" class="btn btn-success" value="Adicionar">
        </form>
    </div>
{% endblock %}